theme: jekyll-theme-slate
title: Sara Taloumis
description: Welcome to my page – This is my work that I've done in Bioinformatics! I will explain the analysis that I've done and give a little information about myself. I have done analysis on Penguins, Oregon Spotted Frogs, and RNA sequences.
